// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_default");
	character\_utility_mp::attachFromArray(xmodelalias\head_allied::main());
	self setViewmodel("xmodel/viewmodel_hands_us");
}

precache()
{
	precacheModel("xmodel/playerbody_default");
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
	precacheModel("xmodel/viewmodel_hands_us");
}
