// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_kriegsmarine");
	character\_utility_mp::attachFromArray(xmodelalias\head_axis::main());
	self.hatModel = "xmodel/equipment_german_kriegsmarine_hat";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_kriegsmarine");
}

precache()
{
	precacheModel("xmodel/playerbody_german_kriegsmarine");
	character\_utility::precacheModelArray(xmodelalias\head_axis::main());
	precacheModel("xmodel/equipment_german_kriegsmarine_hat");
	precacheModel("xmodel/viewmodel_hands_kriegsmarine");
}
