// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_fallschirmjagergrey");
	character\_utility_mp::attachFromArray(xmodelalias\head_axis::main());
	self.hatModel = "xmodel/gear_german_helmet_falshrm_blk";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_fallschirmjager_grey");
	if (character\_utility::useOptionalModels())
	{
		self attach("xmodel/gear_german_load3_falshrm", "", true);
		self attach("xmodel/gear_german_bandolier", "", true);
	}
}

precache()
{
	precacheModel("xmodel/playerbody_german_fallschirmjagergrey");
	character\_utility::precacheModelArray(xmodelalias\head_axis::main());
	precacheModel("xmodel/gear_german_helmet_falshrm_blk");
	precacheModel("xmodel/viewmodel_hands_fallschirmjager_grey");
	if (character\_utility::useOptionalModels())
	{
		precacheModel("xmodel/gear_german_load3_falshrm");
		precacheModel("xmodel/gear_german_bandolier");
	}
}
